### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by holdestmade** [megakid/ha_hildebrand_glow_ihd_mqtt#63]
Getting lots of these in my log (12 per minute) since update to v1.7.0.

Running HA 2024.11.b2

```
2024-11-04 08:27:03.009 ERROR (MainThread) [homeassistant.util.logging] Exception in mqtt_message_received when handling msg on 'glow/xxxxxxxxxxxxxxx/SENSOR/electricitymeter': '{"electricitymeter":{"timestamp":"2024-11-04T08:26:59Z","energy":{"export":{"cumulative":3803.622,"units":"kWh"},"import":{"cumulative":4020.230,"day":10.273,"week":10.273,"month":50.799,"units":"kWh","mpan":"xxxxxxxxxxxxxxx","supplier":"Octopus Energy","price":{"unitrate":0.23510,"standingcharge":0.66260}}},"power":{"value":0.043,"units":"kW"}}}'
Traceback (most recent call last):
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 330, in mqtt_message_received
    updateGroup.process_update(message)
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 393, in process_update
    sensor.process_update(parsed_data)
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 491, in process_update
    ZoneInfo(self._time_zone or self.hass.config.time_zone),
                                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'config'

2024-11-04 08:27:03.039 ERROR (MainThread) [homeassistant.util.logging] Exception in mqtt_message_received when handling msg on 'glow/xxxxxxxxxxxxxxxxxx/SENSOR/gasmeter': '{"gasmeter":{"timestamp":"2024-11-04T08:26:35Z","energy":{"import":{"cumulative":6297.188,"day":2.547,"week":2.547,"month":33.526,"units":"kWh","cumulativevol":561.215,"cumulativevolunits":"m3","dayvol":2.547,"weekvol":2.547,"monthvol":33.526,"dayweekmonthvolunits":"kWh","mprn":"xxxxxxxxxx","supplier":"---","price":{"unitrate":0.06210,"standingcharge":0.29670}}}}}'
Traceback (most recent call last):
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 330, in mqtt_message_received
    updateGroup.process_update(message)
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 393, in process_update
    sensor.process_update(parsed_data)
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 491, in process_update
    ZoneInfo(self._time_zone or self.hass.config.time_zone),
                                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'config'
```
